kind: Service
apiVersion: v1
metadata:
  name: node-red-nodeport
  namespace: windguard
spec:
  type: NodePort 
  ports:
    - name: nodered-port
      nodePort: 31880
      port: 1880
      targetPort: 1880
      protocol: TCP
  selector:
    app: node-red