apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  namespace: mqtt-broker
  labels:
    app: mosquitto
data:
  password.txt: |
    admin:$7$101$nuUyNvx0ri3RLMZy$mXSTTvvdQNLVLb9UMJnl2IUu1hKJU4OVn8dfaP4g50I7JSCzGpJIOxGyG5RiFNwKHG/8rVNZ1RogyyqF4CBwvQ==
